name: Testing

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - uses: actions/setup-go@v5
        with:
          go-version: '^1.23.2'

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test -v ./...